server:
  port: 8082

spring:
  application:
    name: foodCourt

  datasource:
    url: jdbc:postgresql://localhost:5432/foodcourt
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # o update / validate / create-drop
    show-sql: true

  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework.boot.autoconfigure: ERROR

application:
  security:
    jwt:
      secret-key: m2yrnAnikqppG3cqmTOGXExVuVlLxOvaN5q2Gqwel/aigX+wgP68HvbE1ypcpUBv

twilio:
  account:
    sid: ACa25649906639c7fc7cfd53fc37dc7d9e
  auth:
    token: 1b9a0be9cb56960c840e7b6b064a6a8b
  phone:
    number: whatsapp:+14155238886

appdescription: "API management foodCourt"
appversion: "1.0.0"